# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_years', models.IntegerField()),
                ('image_name', models.CharField(max_length=255)),
            ],
        ),
    ]
